BEGIN;

ALTER TABLE notifications
  DROP CONSTRAINT IF EXISTS chk_notification_type;

ALTER TABLE notifications
  ADD CONSTRAINT chk_notification_type
  CHECK (
    type IN (
      'APPOINTMENT_REQUEST_SUBMITTED',
      'APPOINTMENT_REQUEST_CREATED',
      'APPOINTMENT_CONFIRMED',
      'APPOINTMENT_UPDATED',
      'APPOINTMENT_CANCELLED',
      'DENTIST_APPOINTMENT_ASSIGNED',
      'MEDICAL_RECORD_PENDING',
      'MEDICAL_RECORD_CONFIRMED',
      'MEDICAL_RECORD_MISSING',
      'APPOINTMENT_REMINDER',
      'REEXAM_UPCOMING',
      'REEXAM_DUE',
      'REEXAM_OVERDUE'
    )
  );

COMMIT;
